version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme!
    ports:
      - "5432:5432"
    restart: unless-stopped
